# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing CI

on:
  push:
    branches: [ master ]
    paths:
      - src/**/*
      - tests/**/*
      - tsconfig.json
  pull_request:
    branches: [ master ]
    paths:
      - src/**/*
      - tests/**/*
      - tsconfig.json

jobs:
  test:

    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm ci
    - run: npm test
